/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.testng.annotations.*;
import static org.testng.Assert.*;

public class RockPaperScissorsTest {

    @Test public void appHasAGreeting() {

    }

}